Show Ack/Downtime icons in the node tiles for the handled nodes
Icinga/icingaweb2-module-businessprocess pull request #348
Opened 2022-08-22 09:26 UTC by raviks789

In case the hosts/services are acknowledged or have scheduled downtime show Acknowledged or
Downtime icons respectively.

ref #237

2022-08-24 14:24 UTC, flourish86 requested changes
Please add a right margin to the `.actions` container

2022-08-25 08:24 UTC, flourish86 submitted a review, later dismissed
Can you also please remove the right margin in tree view. Thanks!
![Screen Shot 2022-08-25 at 10 13 00](https://user-images.githubusercontent.com/6977434/186612497-84f6de86-0134-4c6f-88d2-20b443a5e43e.png)

2022-08-25 15:43 UTC, raviks789 commented
> Can you also please remove the right margin in tree view. Thanks!

This change will be performed in a new PR as this is not related to the issue in question (ref #237).

2022-08-29 07:46 UTC, nilmerg commented on public/css/module.less
> +                pointer-events: none;
If this wouldn't be an `a`, ignoring pointer events isn't required. Why not just add this class to the `i`?

2022-08-29 07:48 UTC, nilmerg commented on public/css/module.less
> +                &:first-child {
When is this the case?

2022-09-14 07:49 UTC, nilmerg requested changes
The tiles are fine now. Though, we also decided to only show a single icon in the tree view. That's still missing.

2022-09-20 09:28 UTC, raviks789 commented
> The tiles are fine now. Though, we also decided to only show a single icon in the tree view. That's still missing.

This is implemented in #352.

2023-07-25 09:08 UTC, sukhwinder33445 requested changes

2023-07-25 09:08 UTC, sukhwinder33445 commented on library/Businessprocess/Renderer/TileRenderer/NodeTile.php
> +        }
- Please use `ipl/web/Icon`.
- Merge the conditions.

2023-07-28 14:03 UTC, sukhwinder33445 approved these changes

2023-08-03 12:52 UTC, nilmerg approved these changes

2023-08-03 12:53 UTC, merged