Show `Ack` icon in tree view for nodes with both downtime and acknowledgement
Icinga/icingaweb2-module-businessprocess pull request #352
Opened 2022-09-20 09:27 UTC by raviks789

Acknowledgement takes priority in handled nodes and hence it is sufficient to show acknowledged icons in case the handled node has an acknowledgement and also a downtime is scheduled for it.

This change has already been implemented for tiles in #348

## Before
<img width="1026" alt="Screenshot 2022-09-20 at 11 08 57" src="https://user-images.githubusercontent.com/33730024/191221208-fe4d53fb-4bb3-411b-b1ec-a6be499a9b0e.png">

## After
<img width="1026" alt="Screenshot 2022-09-20 at 11 20 04" src="https://user-images.githubusercontent.com/33730024/191221324-1ffbf95d-4f64-48e2-b027-461bebcc14bf.png">

2023-07-25 09:29 UTC, sukhwinder33445 commented on public/css/module.less
> +            margin-right: 0;
Why do you add this?

2023-07-25 09:30 UTC, sukhwinder33445 requested changes

2023-07-26 08:10 UTC, raviks789 commented on public/css/module.less
> +            margin-right: 0;
Generalized the css rule to remove margin-right for icons after state-badges.

2023-07-28 14:11 UTC, sukhwinder33445 requested changes

2023-07-28 14:11 UTC, sukhwinder33445 commented on library/Businessprocess/Renderer/TreeRenderer.php
>              $icons[] = Html::tag('i', ['class' => 'icon icon-ok']);
Please use `Icon` class instead.

2023-08-03 13:01 UTC, nilmerg approved these changes

2023-08-03 13:01 UTC, merged