Do not allow special characters in the node ID
Icinga/icingaweb2-module-businessprocess pull request #354
Opened 2022-09-27 09:09 UTC by sukhwinder33445

fixes #312

2023-07-24 11:58 UTC, nilmerg requested changes

2023-07-24 11:58 UTC, nilmerg commented on application/forms/AddNodeForm.php
> +                        'pattern' => '/^[a-zA-Z0-9](?:[a-zA-Z0-9 ._-]*)?[a-zA-Z0-9_]$/',
This allows the underscore also at the end.

2023-07-24 11:58 UTC, nilmerg commented on application/forms/AddNodeForm.php
> +                                Space, dot, dash and underscore are allowed but not at the beginning or end'
Close parts of multiline strings properly.

e.g.
```
call(
    'foo'
    . ' bar'
);
```

2023-07-24 11:58 UTC, nilmerg commented on application/forms/AddNodeForm.php
> +                                Space, dot, dash and underscore are allowed but not at the beginning or end'
Adjust this every where else in your changes as well.

2023-07-24 11:58 UTC, nilmerg commented on application/forms/AddNodeForm.php
> +                        return (bool) preg_match('/^(?:(?!;).)*$/', $values[0]); // object name contains semicolon
`strpos() === false`

2023-07-24 11:58 UTC, nilmerg commented on application/forms/AddNodeForm.php
> +                        'pattern' => '/^(?:(?!;).)*$/',
`strpos() === false`

2023-07-24 11:58 UTC, nilmerg commented on application/forms/EditNodeForm.php
> +                        'pattern' => '/^(?:(?!;).)*$/',
`strpos() === false`

2023-07-28 11:08 UTC, sukhwinder33445 commented on application/forms/AddNodeForm.php
> +                        return substr_count(';', $value) === 2;
oops, but now it should work properly.

2023-08-01 09:12 UTC, nilmerg commented on application/forms/AddNodeForm.php
> +                        'pattern'   => '/^[a-zA-Z0-9](?:[\w\h.-]*)?[a-zA-Z0-9]$/',
This still allows a trailing underscore. Just did a test and hosts/services as well as processes can have a trailing underscore while on master. What's the issue with it?
https://github.com/Icinga/icingaweb2-module-businessprocess/blob/da2ed1aef4848bfa8194f40de423337f9d4373e6/application/forms/BpConfigForm.php#L29

2023-08-08 06:46 UTC, closed without merging