Clean orphaned (missing) nodes
Icinga/icingaweb2-module-businessprocess pull request #355
Opened 2022-09-27 13:57 UTC by sukhwinder33445

resolves #222

2022-09-30 08:20 UTC, sukhwinder33445 commented
Changes note:
When the process contains linked nodes (in which nodes are missing), 
 only the `Show` link is displayed. If there are no linked missing nodes, but the process contains direct missing nodes, the `Cleanup` link is displayed.

This is necessary because the process cannot differentiate between direct missing nodes and linked missing nodes.

2022-10-04 10:30 UTC, raviks789 submitted a review, later dismissed

2023-07-19 13:39 UTC, nilmerg requested changes

2023-07-19 13:39 UTC, nilmerg commented on application/forms/CleanupNodeForm.php
> +                    'style'        => 'width: 25em',
nah, csp and so on, you know ;)

2023-07-19 13:39 UTC, nilmerg commented on application/forms/CleanupNodeForm.php
> +    protected $parentNode;
seems to be unused

2023-07-19 13:39 UTC, nilmerg commented on application/clicommands/CleanupCommand.php
> +                    $bp = $this->storage->loadProcess($configName);
`listAllMissingChildren` did all of this already. Cache it. Use it. Or just merge the two methods, or use a generator. Just be more efficient please.

2023-07-19 13:39 UTC, nilmerg commented on application/clicommands/CleanupCommand.php
> +            }
include the config name. If none is passed, there's no way of knowing which config was involved later on.

2023-07-27 12:08 UTC, nilmerg requested changes

2023-07-27 12:08 UTC, nilmerg commented on application/clicommands/CleanupCommand.php
> +                    $bp->clearAppliedChanges();
Please check the indentation.

2023-07-27 12:08 UTC, nilmerg commented on application/clicommands/CleanupCommand.php
> +                    );
Please check the indentation.

2023-07-27 12:08 UTC, nilmerg commented on application/clicommands/CleanupCommand.php
> +                $removedNodes = false;
Don't do this. There is no reason not to log that no missing nodes are found. If no config is readable, of course none are found.

2023-08-01 09:22 UTC, nilmerg requested changes
Also, please rebase

2023-08-01 09:22 UTC, nilmerg commented on application/controllers/ProcessController.php
> +                                    'Linked node %s has %d missing child node: {{#link}}Show{{/link}}',
~~%d~~one

2023-08-01 09:22 UTC, nilmerg commented on application/controllers/ProcessController.php
> +                                ['link' => new Link(null, (string)$link)]
Space after casts

2023-08-01 09:22 UTC, nilmerg commented on application/controllers/ProcessController.php
> +                        ['link' => new Link(null, (string)$link)],
space after casts

2023-08-01 09:22 UTC, nilmerg commented on application/forms/CleanupNodeForm.php
> +            FormattedString::create($this->translate('Cleanup missing nodes'))
That's not a formatted string, but just a string.

2023-08-01 09:22 UTC, nilmerg commented on application/forms/CleanupNodeForm.php
> +            FormattedString::create($this->translate('Cleanup missing nodes'))
My previous comment was connected to this being a string, not `ValidHtml`.

2023-08-03 08:50 UTC, nilmerg approved these changes

2023-08-03 08:51 UTC, merged