IcingaDbState: `last_state_change` is now a DateTime Obj
Icinga/icingaweb2-module-businessprocess pull request #374
Opened 2023-06-06 13:10 UTC by sukhwinder33445

ref https://github.com/Icinga/icingadb-web/pull/753

fixes #373

2023-06-06 13:31 UTC, nilmerg approved these changes

2023-06-06 13:33 UTC, lippserd commented
Doesn't this have to be implemented backwards compatible?

2023-06-06 13:36 UTC, nilmerg requested changes
I don't think so, an upgrade to Icinga DB Web 1.1 isn't that much of a deal. But we should require this, so please adjust module.info accordingly.

2023-06-06 13:39 UTC, lippserd commented
> I don't think so, an upgrade to Icinga DB Web 1.1 isn't that much of a deal. But we should require this, so please adjust module.info accordingly.

Sounds good to me.

2023-06-07 06:29 UTC, nilmerg approved these changes

2023-06-07 06:29 UTC, merged