Show node id in edit mode
Icinga/icingaweb2-module-businessprocess pull request #382
Opened 2023-07-13 11:02 UTC by sukhwinder33445

2023-07-13 11:15 UTC, sukhwinder33445 commented
I think if checks for `$this->node !== null` are redundant, since this form is only used for node modification. I cannot find any other use for it. Do you have any idea what this check is used for?

2023-07-17 11:46 UTC, nilmerg requested changes

2023-07-17 11:46 UTC, nilmerg commented on application/forms/ProcessForm.php
> +            'required'      => $this->node !== null,
Just use `true` here.

2023-07-17 11:46 UTC, nilmerg commented on application/forms/ProcessForm.php
> +            'readonly'      => $this->node === null,
Setting `readonly` to anything else than `null` causes it to be effective. Ensure that this is only effective when you want. (Ignoring the fact, that this form isn't used for *new* processes for now)

2023-07-20 11:31 UTC, merged